export const ErrorCode = {
  ERR_ALREADY_TAKEN_USER: 'Username is already taken',
  ERR_ALREADY_IN_USE_EMAIL: 'Email is already in use',
  ERR_USER_LOGIN_FAIL: 'Invalid username/email or password',
  ERR_USER_REGISTER_FAIL: 'Register failed',
  ERR_CONVERT_DTO_ENTITY_FAIL: 'Fail to convert your data at server',
  ERR_WORK_NOT_FOUND: 'Work is not found',
  ERR_CREATE_WORK_FAIL: 'Fail to create work',
  ERR_WORK_LOADED_FAIL: 'Fail to load work',
  ERR_WORK_LIST_NOT_FOUND: 'List of works is not found',
  ERR_WORK_LIST_LOADED_FAIL: 'Fail to load list of works',
  ERR_WORK_UPDATE_FAIL: 'Fail to update work',
  ERR_WORK_DELETE_FAIL: 'Fail to delete work',
  ERR_LABEL_NOT_FOUND: 'Label is not found',
  ERR_CREATE_LABEL_FAIL: 'Fail to create label',
  ERR_LABEL_LIST_NOT_FOUND: 'List of labels is not found',
  ERR_LABEL_LIST_LOADED_FAIL: 'Fail to load list of labels',
  ERR_LABEL_UPDATE_FAIL: 'Fail to update label',
  ERR_LABEL_DELETE_FAIL: 'Fail to delete label',
  ERR_COLOR_NOT_FOUND: 'Color is not found',
  ERR_CREATE_COLOR_FAIL: 'Fail to create color',
  ERR_COLOR_LIST_NOT_FOUND: 'List of colors is not found',
  ERR_COLOR_LIST_LOADED_FAIL: 'Fail to load list of colors',
  ERR_COLOR_UPDATE_FAIL: 'Fail to update color',
  ERR_COLOR_DELETE_FAIL: 'Fail to delete color',
};
