export const SuccessCode = {
  USER_REGISTER_SUCCESS: 'User registered successfully',
  USER_LOGOUT_SUCCESS: "You've been signed out",
  USER_LOGIN_SUCCESS: 'You are logged in',
  WORK_LOADED_SUCCESS: 'Load work successfully',
  WORK_LIST_LOADED_SUCCESS: 'Load list of works successfully',
  WORK_CREATE_SUCCESS: 'Create work successfully',
  WORK_UPDATE_SUCCESS: 'Update work successfully',
  WORK_DELETE_SUCCESS: 'Delete work successfully',
  LABEL_LOADED_SUCCESS: 'Load label successfully',
  LABEL_LIST_LOADED_SUCCESS: 'Load list of labels successfully',
  LABEL_CREATE_SUCCESS: 'Create label successfully',
  LABEL_UPDATE_SUCCESS: 'Update label successfully',
  LABEL_DELETE_SUCCESS: 'Delete label successfully',
  COLOR_LOADED_SUCCESS: 'Load color successfully',
  COLOR_LIST_LOADED_SUCCESS: 'Load list of colors successfully',
  COLOR_CREATE_SUCCESS: 'Create color successfully',
  COLOR_UPDATE_SUCCESS: 'Update color successfully',
  COLOR_DELETE_SUCCESS: 'Delete color successfully',
};
